spring:
  application:
    name: product

  #datasource:
  #  url: jdbc:mysql://115.138.67.190/scent_product?autoReconnect=true&useSSL=false&characterEncoding=utf8
  #  username: root
  #  password: anstbzmfla
  #  driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:testdb"
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
  redis:
    host: localhost
    port: 6379
  profiles:
    active: local

