spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://115.138.67.190/scent_product?autoReconnect=true&useSSL=false&characterEncoding=utf8
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: false
  redis:
    host: localhost
    port: 6379
  profiles:
    active: local
